"""empty message

Revision ID: dfa28088af6d
Revises: 
Create Date: 2022-05-31 01:02:36.010501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa28088af6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('fecha_ing', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apellido'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fecha_ing'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('calificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calificacion', sa.String(length=50), nullable=False),
    sa.Column('comentario', sa.String(length=250), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('falla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('modelo', sa.String(length=120), nullable=False),
    sa.Column('fecha_creacion', sa.Integer(), nullable=False),
    sa.Column('fecha_cierre', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=5), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfil_tecnico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('historial', sa.String(length=120), nullable=False),
    sa.Column('ubicacion', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descripcion'),
    sa.UniqueConstraint('historial'),
    sa.UniqueConstraint('url')
    )
    op.create_table('propuesta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detalle', sa.String(length=120), nullable=False),
    sa.Column('costo_servicio', sa.String(length=80), nullable=False),
    sa.Column('estado', sa.String(length=120), nullable=False),
    sa.Column('id_falla', sa.Integer(), nullable=True),
    sa.Column('id_tecnico', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_falla'], ['falla.id'], ),
    sa.ForeignKeyConstraint(['id_tecnico'], ['perfil_tecnico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detalle'),
    sa.UniqueConstraint('estado')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('propuesta')
    op.drop_table('perfil_tecnico')
    op.drop_table('falla')
    op.drop_table('calificacion')
    op.drop_table('user')
    # ### end Alembic commands ###
